// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofkaeprtlfaeceilypra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ma2FlcHJ0bGZhZWNlaWx5cHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjg1MDcsImV4cCI6MjA2MDY0NDUwN30.9hYYl8qqCa8cXUrCbaiIHd4QDZsL_T3hIhAZ0sngTbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});